site_name: Blender SPA User Documentation
site_url: https://the-spa-studios.github.io/blender-spa-userdoc/
nav:
  - Introduction: index.md
  - Layout Guide: layout.md
  - Animation Guide: anim.md
  - About:
      - The SPA Studios: about/studio.md
      - Contributing: about/contributing.md
      - License: about/license.md
theme: readthedocs
